# Generated by Django 4.1.7 on 2023-02-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profiles_photo/no_user.png', upload_to='profile_photos'),
        ),
    ]
