version: '3.3'
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    network_mode: "host"
    image: app:django
    container_name: Blog
    command: python3 manage.py runserver