version: '3.3'
services:
  app:
    build: .
    volumes:
      - .:/Spablog
    ports:
      - 8000:8000
    network_mode: "host"
    image: app:SpaBlogSqlite
    container_name: SpaBlogSqlite
    command: python3 manage.py runserver